pharmaverse/datacutr

R/drop_temp_vars.R

This is an initial draft of the drop_temp_vars function. I am merging it to devel so that @alanaharris22 and @barnett11 can use this function within their own code. 
This function is NOT final, it still needs to be updated to add assertions and also to use the correct package formatting.

2-remove-temp-vars-function

---

R/drop_temp_vars.R
R/pt_cut.R

This is an initial draft of the pt_cut function, merging to devel so that @reesnj  and @barnett11 can use this function within their own code. This function is NOT final.

6 patient cut function

---

R/sdtm_cut.R

This is an initial draft of the sdtm_cut function, merging to devel so that @reesnj and @barnett11 can use this function within their own code. This function is NOT final.

7_SDTMv-cut-function

---

R/special_dm_cut.R
inst/templates/datacutr_template.R

Merging for devel sharing purposes only - NOT complete yet
#5 
#4

5_special_dm

---

R/pt_cut.R

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Updating example

---

R/dev_utils.R
R/pt_cut.R
R/sdtm_cut.R

Merging with devel so others can use latest versions of this code.

Adding in quo_c function and updating pt_cut and sdtm_cut to use this.

---

DESCRIPTION
R/pt_cut.R
man/pt_cut.Rd

Merging to devel so others can use the latest version of this function.

Updating patient cut function to output flag

---

R/pt_cut.R
R/sdtm_cut.R
docs/articles/git_usage.html
docs/pkgdown.yml
docs/reference/pt_cut.html
docs/reference/quo_c.html
docs/reference/sdtm_cut.html
docs/reference/special_dm_cut.html
man/pt_cut.Rd
man/sdtm_cut.Rd
tests/testthat/test-pt_cut.R
tests/testthat/test-sdtm_cut.R

Merging with devel for other developers to use

Adding unit tests for sdtm_cut, and updating examples

---

R/special_dm_cut.R
tests/testthat/test-special_dm_cut.R

Not final - pushing into devel for sharing and preparing overall script

5 special dm

---

R/special_dm_cut.R

Updates special dm function for practice cases in devel

Add attributes statement so that left_join creates no warning #5

---

R/special_dm_cut.R

For merging into devel for use

Change dset references to variable references instead #5

---

R/special_dm_cut.R

Update DCUTDTM reference to be cut_var instead #5

---

R/process_cut.R
man/process_cut.Rd
man/special_dm_cut.Rd

Updated process_cut function due to updates made to special_dm_cut function - #69

Updated process_cut function due to updates made to special_dm_cut function. 

---

R/process_cut.R
man/process_cut.Rd

Updated process_cut function #69 to also return DCUT + any uncut SDTMs. Merging to devel so that this updated function can be used within the 4_scripts branch, not yet final.

Updated process_cut function to also return DCUT + any uncut SDTMs

---

vignettes/datacutr.Rmd

Description of data cut process added #77

---

renv.lock

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Updating DT package version

---

.github/pull_request_template.md
R/drop_temp_vars.R
inst/templates/dummy_data.R
tests/testthat/test-create_dcut.R
tests/testthat/test-date_cut.R
tests/testthat/test-drop_temp_vars.R
tests/testthat/test-pt_cut.R
tests/testthat/test-special_dm_cut.R
vignettes/datacutr.Rmd
vignettes/modular.Rmd

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Updating for lintr.

---

_pkgdown.yml
vignettes/datacutr.Rmd
vignettes/variable_cut.Rmd

Variable Date Cut vignette #90

---

README.md
vignettes/contribution_model.Rmd

Documentation updates

---

R/date_cut.R
R/special_dm_cut.R

116 dcutdate assertion

---

vignettes/examplemodular.Rmd
vignettes/examplewrapped.Rmd
vignettes/modular.Rmd
vignettes/variable_cut.Rmd
vignettes/wrapper.Rmd

Update ds source and variable update of DCUTDTC to be character

---

tests/testthat/test-drop_temp_vars.R
tests/testthat/test-impute_dcutdtc.R
tests/testthat/test-process_cut.R
tests/testthat/test-special_dm_cut.R

Adds more detail around test_that functions

---

_pkgdown.yml
tests/testthat/test-special_dm_cut.R

Fixing link issue and bug in testthat test

Fixing link issue and bug in test

---

.github/workflows/common.yml

Resolves the issue that @alanaharris22 mentioned in https://github.com/pharmaverse/datacutr/pull/133#issuecomment-1437384293

Set default landing page as devel

---

R/impute_dcutdtc.R
R/impute_sdtm.R
docs/pkgdown.yml
man/impute_dcutdtc.Rd
man/impute_sdtm.Rd
tests/testthat/test-impute_dcutdtc.R
tests/testthat/test-impute_sdtm.R
vignettes/variable_cut.Rmd

Upating bug in variable_cut.Rmd preventing site from being built

Upating bug in variable_cut.Rmd

---

.gitignore
docs/pkgdown.yml

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

124 pt cut updates

---

R/apply_cut.R
R/create_dcut.R
R/date_cut.R
R/impute_dcutdtc.R
R/impute_sdtm.R
R/process_cut.R
R/special_dm_cut.R

Updating quo_c references which are no longer needed.

Updating quo_c references which are no longer needed.

---

R/create_dcut.R
man/create_dcut.Rd

Updating comments as per [#157](https://github.com/pharmaverse/datacutr/issues/157)
FYI @reesnj - thanks for reviewing!

157 peer review create_dcut

---

.Rbuildignore
DESCRIPTION
README.md
cran-comments.md
man/datacutr-package.Rd

CRAN prep Closes #162

---

DESCRIPTION
README.md
vignettes/examplemodular.Rmd
vignettes/examplewrapped.Rmd
vignettes/modular.Rmd
vignettes/variable_cut.Rmd
vignettes/wrapper.Rmd

Updates description and readme 

---

.lintr
DESCRIPTION
NEWS.md
man/datacutr-package.Rd

@barnett11 Added some minor updates to `DESCRIPTION` file here. Also updated to version 0.2.0 ahead of your next release that would include these updates and started changelog section in `NEWS.md` for that release, but you’ll need to add anything else from you other updates made for PRs merged since 0.1.0. Just need to make one more commit here for the man files and then will add you as a reviewer.
Thank you for your Pull Request! [admiraldev](https://pharmaverse.github.io/admiraldev/devel/index.html) have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code …

closes #182 riskmetric updates

---

NEWS.md
_pkgdown.yml

Fixing source link

---

NEWS.md
R/impute_dcutdtc.R
man/impute_dcutdtc.Rd
renv.lock
tests/testthat/test-impute_dcutdtc.R

189 impute dcutdtc missing dcutdtc

---

.lintr
NEWS.md
R/create_dcut.R
man/create_dcut.Rd
tests/testthat/test-create_dcut.R

190 update create dcut for handling missing datacut date

---

renv.lock

Closes #203 Adding packages

---

_pkgdown.yml
renv.lock

Closes #206 pkgbuild issues

---

.github/workflows/common.yml

Closes #206 Update CICD from admiral

---

README.md

Update minor spelling

---

.github/workflows/common.yml
README.md

Add devel to cicd trigger

---

renv.lock

Closes #206 Change RSPM ref to CRAN

---

R/read_out.R

Closes #219 - Remove spaces and colons from readout html file

---

README.md

Devel to Main

---

.Rbuildignore
.gitignore
DESCRIPTION
NEWS.md

Upversion to 0.2.1 for submission to CRAN

---

README.md

Fix link to coverage badge

---

DESCRIPTION
NEWS.md
R/read_out.R

Closes #233 knitr issue

---

DESCRIPTION
NEWS.md

Closes #236 Amend version from 0.2.2.1 to 0.2.3
